name: Update README with GitHub Activity

on:
  schedule:
    - cron: '0 0 * * 0' # Runs at 00:00 UTC every Sunday
  workflow_dispatch: # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README with recent activity
    permissions:
      contents: write # This is important to allow the action to commit changes

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          COMMIT_MSG: 'Update README with recent activity'
          MAX_LINES: 5