name: Update README with Latest Blog Posts

on:
  schedule:
    - cron: '0 12 * * *' # Runs every day at 12:00 UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme-with-blog:
    name: Update README with Latest Blog Posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          feed_list: "https://davidwagih.substack.com/feed" # Replace 'yourusername' with your actual Substack username
          max_post_count: 5
          commit_message: "Update README with latest Substack posts"
          gh_token: ${{ secrets.ACCESS_TOKEN }}